// src/components/header.svelte
<script lang="ts">
  import menu from "$lib/assets/icons/menu.svg";
  import logo from "$lib/assets/logo.svg";
</script>

<header class="w-full h-auto flex items-center justify-space-between">
  <div class="w-full h-8">
    <img alt="HitColor logo" src={logo} class="w-auto h-full" />
  </div>

  <div class="w-auto h-8 flex items-center justify-center p-1">
    <img src={menu} alt="" class="w-auto h-full" />
  </div>
</header>

// src/components/header.tsx
import logoHitcolor from '../assets/logo-hitcolor.svg'
import { Drawer } from './Drawer'

export const Header = () => {
  return (
    <header className='w-full flex items-center justify-between p-4 border border-hitcolor-800'>
      <div className='w-auto h-6 flex items-center justify-center'>
        <img src={logoHitcolor} className='w-auto h-full' />
      </div>

      <Drawer />
    </header>
  )
}
